---
title: Software Ecosystem
---

%%{init: {"flowchart": {"nodeSpacing": 34, "rankSpacing": 44}, "themeCSS": ".nodeLabel, .edgeLabel, .cluster-label { font-size: 20px !important; font-weight: 700 !important; }"}} }%%
flowchart TB

subgraph Diagram[" "]
    direction LR

%% Users
    Investigators[Investigators]
    Operations[Laboratory Operations]
    CustomerService[Customer Service & Project Management]
    Consortium[MMRRC / IMPC / MBP Programs]
    YouTrack[YouTrack Ticketing System]

%% Core systems
    subgraph Core["Integrated Scientific Workflow Infrastructure"]
        direction TB
        MMPCLive[MMPC-Live\nMetabolic Phenotyping]
        Pheno[Pheno-LIMS\nPhenotyping]
        Geno[Geno-LIMS\nGenotyping]
        Repro[Repro-LIMS\nIn Vivo Engineering & RT]
    end

%% External systems
    subgraph External[" "]
        direction TB
        MMPCOrders[MMPC-Live Orders]
        Mosaic[Mosaic Vivarium System]
        OTS[MMRRC Order Tracking]
        PTS[Project Tracking System]
        DCC[IMPC / External Data Resources]
        MGI[MGI]
        MMRRCRepository[MMRRC Repository]
        Cryo[Cryogenic Inventory]
        Publications[Publications & Reporting]
    end

%% User interactions
    Investigators <--> Core
    Operations --> Core
    CustomerService <--> Core
    Consortium <--> Core
    YouTrack <--> Core

%% Internal interactions
    MMPCLive <--> Pheno
    Pheno <--> Geno
    Geno <--> Repro
    Repro <--> Pheno

%% External integrations
    Core <--> MMPCOrders
    Core <--> Mosaic
    Core <--> OTS
    Core <--> PTS
    Core <--> DCC
    Repro <---> MGI
    Repro --> MMRRCRepository
    Repro --> Cryo
    Core --> Publications

    style External fill:none,stroke:none
end

Diagram ~~~ Footnote["Figure 1."]

style Diagram fill:none,stroke:none
style Footnote fill:none,stroke:none
